config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'home#index'

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
    get 'sign_out' => 'devise/sessions#destroy'
  end

  resources :competitions do
    resources :weight_records
  end
  resources :enrollments, only: [:create, :destroy, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/competition.rb
class Competition < ApplicationRecord
  has_many :competitors
  has_many :weight_records
  has_many :users, through: :weight_records
end

app/models/competitor.rb
class Competitor < ApplicationRecord
  belongs_to :user
  belongs_to :competition
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :competitors
  has_many :competitions, through: :competitors
  has_many :weight_records
end

app/models/weight_record.rb
class WeightRecord < ApplicationRecord
  belongs_to :user
  belongs_to :competition

  validates :weight, presence: true, numericality: true
  validates :effective_date, presence: true

  scope :default_order, -> { order(effective_date: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  include CompetitionsHelper

  def index
    @competitions = Competition.all
  end

  def show
    @competition = Competition.find(params[:id])
  end

  def new
    @competition = Competition.new
  end

  def create
    @competition = current_user.competitions.build(competition_params)

    if @competition.save
      flash[:success] = "Competition '#{@competition.title}' created!"
      redirect_to @competition
    else
      flash[:alert] = "Some error!"
      render 'new'
    end
  end

  private

  helper_method def earliest_and_latest_weight_record_by_user
    @earliest_and_latest_weight_record_by_user || begin
     @competition.weight_records.preload(:user).default_order.group_by(&:user).map do |user, weight_records|
      [
        user,
        {
          earliest: weight_records.last,
          latest: weight_records.first
        }
      ]
     end.to_h
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      redirect_to competitions_path
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit( :name, 
                                  :email, 
                                  :password, 
                                  :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit( :name, 
                                  :email, 
                                  :password, 
                                  :password_confirmation, 
                                  :current_password)
  end
end

app/controllers/weight_records_controller.rb
class WeightRecordsController < ApplicationController
  def new
    @weight_record = competition.weight_records.build(
      effective_date: Time.zone.now
    )
  end

  def create
    @weight_record = competition.weight_records.build(weight_record_params)
    @weight_record.user = current_user

    if @weight_record.save
      flash[:success] = "Weight Recorded for '#{@competition.title}'!"
      redirect_to competition_path(competition)
    else
      flash[:alert] = "Unable to create Weight Record!"
      render 'new'
    end
  end

  private

  def competition
    @competition ||= Competition.find(params[:competition_id])
  end

  def weight_record_params
    params.require(:weight_record).permit(:weight, :effective_date)
  end
end

app/helpers/application_helper.rb
require 'navigation_helper.rb'

module ApplicationHelper
  include NavigationHelper
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
  def competition_params
    params.require(:competition).permit(:title, :start_date, :finish_date)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/navigation_helper.rb
module NavigationHelper

  def collapsible_links_partial_path
    if user_signed_in?
      'layouts/navigation/collapsible_elements/signed_in_links'
    else
      'layouts/navigation/collapsible_elements/non_signed_in_links'
    end
  end

end

app/views/competitions/_form.html.erb
<%= form_with(model: @competition, local: true) do |f| %>
  <div class="container">
    <div class="title">
      <%= f.label :title, class: "form-label" %>
      <%= f.text_field :title, class: "form-control", placeholder: "Enter the Competition Title", autofocus: true %>
    </div>

    <div class="start-date">
      <%= f.label :start_date, class: "form-label" %>
      <%= f.date_field :start_date, type: "date", class: "form-control" %>
    </div>

    <div class="finish-date">
      <%= f.label :finish_date, class: "form-label" %>
      <%= f.date_field :finish_date, type: "date", class: "form-control" %>
    </div>

    <div class="submit-cancel">
      <%= f.submit "Create Competition", class:"btn btn-success" %>
      <%= link_to 'Cancel', root_path, class:"btn btn-danger" %>
    </div>
  </div>
<% end %>

app/views/competitions/index.html.erb
<div class="container">
  <h2>Competitions</h2>
  <%= link_to 'New Competition', new_competition_path(), class: "btn btn-success" %>
  <div class="table-responsive">          
    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Start Date</th>
          <th>Finish Date</th>
        </tr>
      </thead>
      <tbody>
        <% @competitions.each do |competition| %>
          <tr>
            <td><%= link_to competition.title, competition_path(competition) %></td>
            <td><%= competition.start_date %></td>
            <td><%= competition.finish_date %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/competitions/new.html.erb
<div class="container">
  <h2 class="title">Create Competition</h2>
  <%= render 'form' %>
</div>

app/views/competitions/show.html.erb
<div class="container">
  <h2><%= @competition.title %></h2>
  <%= link_to 'New Weight Record', new_competition_weight_record_path(@competition), class: "btn btn-success" %>

  <div>
    <span class="badge bg-secondary"><%= @competition.start_date %> to <%= @competition.finish_date %></span>
  </div>

  <%= line_chart @competition.weight_records.group_by(&:user).map { |user, weight_records|
      {name: user.name, data: weight_records.pluck(:effective_date, :weight)}
  } %>

  <div class="container">
    <h2>Competitors</h2>
    <div class="table-responsive">
      <table class="table" id="sortTable">
        <thead>
          <tr>
            <th data-field="name">Competitor</th>
            <th data-field="weight">Starting Weight</th>
            <th data-field="weight">Most Recent Weight</th>
            <th data-field="weight">Difference</th>
            <th data-field="weight">Percent Lost</th>
          </tr>
        </thead>
        <tbody>
          <% earliest_and_latest_weight_record_by_user.each do |user, weight_records| %>
            <% earliest = weight_records[:earliest] %>
            <% latest = weight_records[:latest] %>
            <tr>
              <td><%= user.name %></td>
              <td><%= earliest.weight %>kg</td>
              <td><%= latest.weight %>kg</td>
              <td><%= latest.weight - earliest.weight %>kg</td>
              <td><%= ((100 - (latest.weight / earliest.weight) * 100)).round(2) %>%</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <br/>

  <div class="container">
    <h2>Weigh Ins</h2>
    <div class="table-responsive">
      <table class="table" id="sortTable">
        <thead>
          <tr>
            <th data-field="date" data-sortable="true" >Date</th>
            <th data-field="name">Competitor</th>
            <th data-field="weight">Weight</th>
          </tr>
        </thead>
        <tbody>
          <% @competition.weight_records.preload(:user).default_order.each do |record| %>
            <tr>
              <td><%= record.effective_date %></td>
              <td><%= record.user.name %></td>
              <td><%= record.weight %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/home/index.html.haml
.container
  %h2 Welcome to LoseIt
  %h3 Sign Up now to join in the competition!

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="row">

      <!-- Elements visible all the time -->
      <div class="col-sm-7">
        <%= render 'layouts/navigation/header' %>
      </div><!-- col-sm-7 -->

      <!-- Elements collapses on smaller devices -->
      <div class="col-sm-5">
        <%= render 'layouts/navigation/collapsible_elements' %>
      </div><!-- col-sm-5 -->

    </div><!-- row -->
  </div><!-- container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loseit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/navigation/_collapsible_elements.html.erb
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse navbar-right" id="navbar-collapsible-content">
  <ul class="nav navbar-nav ">
    <%= render collapsible_links_partial_path %>
  </ul>
</div><!-- navbar-collapse -->

app/views/layouts/navigation/_header.html.erb
<div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapsible-content" aria-expanded="false">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <%= link_to 'LoseIt', root_path, class: 'navbar-brand' %>
</div>

app/views/layouts/navigation/collapsible_elements/_non_signed_in_links.html.erb
<li ><%= link_to 'Log In', login_path %></li>
<li ><%= link_to 'Sign Up', signup_path %></li>

app/views/layouts/navigation/collapsible_elements/_signed_in_links.html.erb
<li class="dropdown pc-menu">
  <a id="user-settings" class="dropdown-toggle" data-toggle="dropdown" href="#">
    <span id="user-name"><%= current_user.name %></span>
    <span class="caret"></span>
  </a>

  <ul class="dropdown-menu" role="menu">
    <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
    <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
  </ul>
</li>

<li class="mobile-menu">
  <%= link_to 'Edit Profile', edit_user_registration_path %>
</li>
<li class="mobile-menu">
  <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
</li>

app/views/weight_records/new.html.haml
.container
  %h2.title New Weight Record for #{@competition.title}

  = form_with model: [:competition, @weight_record]  do |f|
    = f.label :weight, class: "form-label"
    = f.number_field :weight, class: "form-control", step: 0.1
    = f.label :effective_date, class: "form-label"
    = f.date_field :effective_date, class: "form-control"

    = f.submit 'Create Weight Record', class: "btn btn-success"
    = link_to 'Cancel', @competition, class: "btn btn-danger"